### ISSUE TITLE
include q2-woltka at https://library.qiime2.org/plugins/

### ISSUE THREAD

**Issue by Mechah** [qiyunzhu/woltka#119]
Hi,
first of all, thanks for developing q2-woltka!
I was just surprised that q2-woltka was not included on the QIIME2 plugin Library webpage.
Is there a reason why it is not promoted there as well?

**Comment by qiyunzhu** [comment]
Hello @Mechah That's a good idea! I am surprised why I haven't tried that already. Let us get to it!
