### ISSUE TITLE
Woltka tools collapse

### ISSUE THREAD

**Issue by thompsrs** [qiyunzhu/woltka#130]
I'm using the woltka tools collapse command: 
woltka tools collapse -i 105951_per-gene.biom -m annotation.txt -o output.biom

annotation file from: https://biocore.github.io/wol/data/markers/

It seems to work but I return 0 features after collapsing:
Number of features before collapsing: 112006.
Collapsing profile... Done.
Number of features after collapsing: 0.
Collapsed profile written.

**Comment by qiyunzhu** [comment]
@thompsrs Thanks for tring our program! This command likely won't work because the annotation file is about **marker** genes used for building the phylogenetic tree, NOT the general genes inferred using the WoL SOP. The latter file(s) can be found in our FTP server or Globus endpoint.
