### ISSUE TITLE
Rigorously define what a 'simple map' is.

### ISSUE THREAD

**Issue by gwarmstrong** [qiyunzhu/woltka#15]
'simple map' is referenced multiple places through the `README`, but it is still unclear to me what is, and is not, a valid 'simple map'.

_Originally posted by @gwarmstrong in https://github.com/qiyunzhu/woltka/pull/1_

**Comment by qiyunzhu** [comment]
Improved the description of "simple map" in multiple places in commit [66cfa9c](https://github.com/qiyunzhu/woltka/pull/1/commits/66cfa9cf115dcdf548fc4ef2baab951442c8a4d9).

The term "simple map" appears multiple times, and they refer to different things. The only common point is that they are all tab-delimited files. I added description to every instance where it occurs, as e.g., "a simple map of query \<tab\> subject". Commit [66cfa9c](https://github.com/qiyunzhu/woltka/pull/1/commits/66cfa9cf115dcdf548fc4ef2baab951442c8a4d9).

I tend to suggest that a simple definition like "query \<tab\> subject" is more acceptable to the general audience than a _rigorous_ definition such as "a UTF8-encoded text file in which each line contains exactly one <tab> between two fields where the first field is a query ID and the second field is a subject ID and either field must not be empty.".

**Comment by gwarmstrong** [comment]
Closed in favor of #16
