### ISSUE TITLE
Finding sequences uploaded on WoL

### ISSUE THREAD

**Issue by JenniferOnuora** [qiyunzhu/woltka#165]
Hi Admin,

I am a Ph.D. student and I will be using Qiita for my shot-gun metagenomic analysis. I have specific species and strains of interest that I would like to investigate their relative abundance.

Since WoL is the reference database embedded on Qiita, how can I proceed to check if the genomes of my strains and species of interest are already uploaded to WoL?

I was directed to submit my request here. Please let me know if you require more explanation.

Regards,
Jennifer

**Comment by JenniferOnuora** [comment]
Hi @qiyunzhu 

I am yet to get a response to my request. It says here on the website that WoL is based on genomes publicly available in the NCBI and Genbank: https://biocore.github.io/wol/start

My genome of interest is already uploaded to NCBI (Accession number: CP063750.1, CP063751.1, and CP063752.1 :(https://www.ncbi.nlm.nih.gov/nuccore/CP063750.1))

Is there no way to update the WoL database to match the update on the NCBI database?

Looking forward to your response.

Regards,
Jennifer

**Comment by qiyunzhu** [comment]
Hi @JenniferOnuora Sorry for overlooking your response. WoL itself cannot be easily updated. But we provide a [protocol](https://github.com/qiyunzhu/woltka/blob/master/doc/refseq.md) for you to generate a custom database based on newest NCBI genomes. Hope it helps!

**Comment by qiyunzhu** [comment]
We created a new method [DEPP](https://academic.oup.com/sysbio/advance-article/doi/10.1093/sysbio/syac031/6575921) to place new genomes into an existing phylogeny. We are testing it on WoL now. In the near future the application you described will become reality.

**Comment by JenniferOnuora** [comment]
Thanks for the clarification. Well appreciated.
