### ISSUE TITLE
Finding strains and sub-species on WoL

### ISSUE THREAD

**Issue by JenniferOnuora** [qiyunzhu/woltka#166]
Hi Admin,

I am a Ph.D. student and I will be using Qiita for my shot-gun metagenomic analysis. I have specific species and strains of interest that I would like to investigate their relative abundance.

Since WoL is the reference database embedded on Qiita, how can I proceed to check if the genomes of my strains and species of interest are already uploaded to WoL?

I was directed to submit my request here. Please let me know if you require more explanation.

Regards,
Jennifer

**Comment by qiyunzhu** [comment]
Duplicate of #165
