### ISSUE TITLE
Data Transformations after Functional classification of genes

### ISSUE THREAD

**Issue by jlabus** [qiyunzhu/woltka#168]
We are interested in the functional potential of our genomes in predicting outcomes. As such the 
 Qiita generated per-gene table was converted to uniref-ids and those to kegg-ids. Not surprisingly the KO dataset is skewed with lots of zeros. I am curious what the recommended transformation is priori to analysis, e,g., centered log transformation.

**Comment by qiyunzhu** [comment]
Hello @jlabus Thanks for your interest in our program. Your question is very important in the field but I am not sure if there is a uniformly accepted answer. Different downstream analyses and tools will have different ways of normalization. For example, if you want to do differential abundance / expression analysis using tools like ANCOM, Masslin2, etc, you can keep the raw counts, as they will do the normalization (if any) as part of their workflow. If you want to do a homebrew analysis, you may need to read around and pick a transformation that's most appropriate for you. For example, in the [HMP2 paper](https://www.nature.com/articles/s41586-019-1237-9), they did an arcsine transformation on the relative abundance data of functional units prior to differential abundance analysis. In some analyses, especially dimensionality reduction and supervised learning, I usually found that centered log-ratio transformation makes more sense. It is an open-ended question that deserves more exploration.
