### ISSUE TITLE
crown is a list

### ISSUE THREAD

**Issue by emikoifish** [qiyunzhu/woltka#35]
https://github.com/qiyunzhu/woltka/blob/4c9101a796a214c877c9bf38348ab15afc012d87/woltka/tree.py#L326

Does crown necessarily need to be a list or could it possibly be a set?

@qiyunzhu @gwarmstrong

**Comment by qiyunzhu** [comment]
@emikoifish I think it is okay to be a `set`. However I guess a `list` is cheaper than a `set`, when the only thing we need to do with it is to push elements into the end of array. But I could be wrong and benchmarks will give the best answer.
