### ISSUE TITLE
Output BIOM?

### ISSUE THREAD

**Issue by antgonza** [qiyunzhu/woltka#4]
Currently, the output is tsv but it might be better to just output a biom or perhaps a qza. However, I might be missing something, so is there any reason to output a tsv?

**Comment by qiyunzhu** [comment]
The standalone version outputs **tsv**, while the QIIME 2 plugin outputs **qza**. I am going to add a mechanism to allow the former do biom too.

**Comment by antgonza** [comment]
I'll argue that for compatibility between tools and to skip one step for users processing, we should only output biom. However, this might depend on the sparsity of the data in the tables; my _only_ test seems to confirm this idea as it saves some space with biom and we have access to quick summaries with this format:
```
$ ls -lah table*
-rw-r--r-- 1 antoniog knightlab 1022K Feb 24 05:22 table.biom
-rw-r--r-- 1 antoniog knightlab  1.4M Feb 23 17:55 table.tsv

$ biom summarize-table -i table.biom | head
Num samples: 150
Num observations: 3,777
Total count: 1,847,340,296
Table density (fraction of non-zero values): 0.250

Counts/sample summary:
 Min: 3,625.000
 Max: 37,014,854.000
 Median: 11,018,002.500
 Mean: 12,315,601.973

$ biom summarize-table --observations -i table.biom | head
Num samples: 150
Num observations: 3,777
Total count: 1,847,340,296
Table density (fraction of non-zero values): 0.250

Counts/sample summary:
 Min: 1.000
 Max: 279,138,293.000
 Median: 75.000
 Mean: 489,102.541
```

**Comment by qiyunzhu** [comment]
Have made BIOM the default output format. Thanks for the information and benchmarking! I agree that compatibility with our other tools is top priority!
