### ISSUE TITLE
Branches confusion master vs. dev?

### ISSUE THREAD

**Issue by antgonza** [qiyunzhu/woltka#5]
It's confusing which branch is the default. Thus, should the dev branch be the default branch? Perhaps merge master and dev? No idea! The issue is that if you are in the dev branch and you click on the wolka repository link at the top, it will take you to the default branch, which is master ...

**Comment by qiyunzhu** [comment]
@antgonza Now the prototype codes are at `dev`, I think that after code review (kindly offered by @gwarmstrong ) we can merge into `master`. After that, new PRs should all go to `master`.

**Comment by antgonza** [comment]
Got it, thanks! I guess this can also be closed once dev becomes master ...

**Comment by qiyunzhu** [comment]
Now everything is updated to the master branch. Thanks to @gwarmstrong 's code review effort! Will work on the master branch (by sending smaller PRs to it) starting from now.
