### ISSUE TITLE
Check for .sam.xz extension when computing number of alignment files to read

### ISSUE THREAD

**Issue by ekopylova** [qiyunzhu/woltka#70]
If I pass a directory ```X``` having 1 alignment file ```.sam.xz``` and 3 non-alignment files (with extensions ```.qza, .html and .biom)``` , then run ```woltka classify``` on ```X```, the stdout reports says ```Number of alignment files to read: 4.```. Not sure if the program goes on to check the file extensions of the 4 files and only works on the one with ```.sam.xz```, however in any case the number of alignment files should be 1.

**Comment by qiyunzhu** [comment]
Hello @ekopylova The solution is to add `--filext .sam.xz` to the command. See [here](https://github.com/qiyunzhu/woltka/blob/master/doc/input.md#filename-pattern).

**Comment by ekopylova** [comment]
Thanks!
