### ISSUE TITLE
parameters for coordinates-based functional classification using MetaCyc

### ISSUE THREAD

**Issue by popucui** [qiyunzhu/woltka#95]
Hi guys,

I'm trying to do coordinates-based functional classification using MetaCyc following the instructions [ from woltka's doc](https://github.com/qiyunzhu/woltka/blob/master/doc/wol.md#sequence-alignment):

```bash
mcdir=annotation/metacyc
woltka classify \
  --input input.sam \
  --coords annotation/coords.txt.xz \
  --map annotation/uniref.map.xz \
  --map $mcdir/protein.map --names $mcdir/protein.names \
  --map $mcdir/protein2enzrxn.map --names $mcdir/enzrxn.names \
  --map $mcdir/enzrxn2reaction.map --names $mcdir/reaction.names \
  --map $mcdir/reaction2pathway.map --names $mcdir/pathway.names \
  --map $mcdir/pathway2class.map --names $mcdir/class.names \
  --map-as-rank \
  --rank protein,enzrxn,reaction,pathway,class \
  --output output_dir
```

It seems that `annotation/coords.txt.xz` and `annotation/uniref.map.xz` are not included in shogun's default database, where I can find these or how can I build it myself if needed?  Thanks a lot!

**Comment by qiyunzhu** [comment]
Hello @popucui Thank you for your interest in our program. These database files are not bundled with SHOGUN, but part of the WoL data release (see the "[Download via Globus](https://biocore.github.io/wol/download#download-via-globus)" section).

**Comment by popucui** [comment]
Thanks a lot @qiyunzhu I'll go ahead and close this issue.

**Comment by qiyunzhu** [comment]
@popucui You are welcome!
