### ISSUE TITLE
Working example for coordinates-based functional classification using MetaCyc

### ISSUE THREAD

**Issue by popucui** [qiyunzhu/woltka#96]
I followed the example commands [in woltka's doc](https://github.com/qiyunzhu/woltka/blob/master/doc/wol.md#sequence-alignment) to do coordinates-based functional classification using MetaCyc. I tried to run it using SRA data from [a paper](https://doi.org/10.1016/j.cell.2020.09.009) and the metagenome data sequenced at our lab, both runs got an empty result.

Here are the commands I used using our lab's data:
```bash
for sample in  A0 A1 A5 A7 A4 A6 A2;
do
mkdir ./metacyc/${sample}
mcdir=/path/to/metacyc/
woltka classify \
  --input ${sample}.bowtie2.sam \
  --coords /path/to/database/WoL/annotation/coords.txt.xz \
  --map /path/to/database/WoL/annotation/uniref.map.xz \
  --map $mcdir/protein.map --names $mcdir/protein.names \
  --map $mcdir/protein2enzrxn.map --names $mcdir/enzrxn.names \
  --map $mcdir/enzrxn2reaction.map --names $mcdir/reaction.names \
  --map $mcdir/reaction2pathway.map --names $mcdir/pathway.names \
  --map $mcdir/pathway2class.map --names $mcdir/class.names \
  --map-as-rank \
  --rank protein,enzrxn,reaction,pathway,class \
  --output ./metacyc/${sample} --to-tsv
done
```

Below is a sample of the output from woltka:
```
Input alignment file: A7.bowtie2.sam.
Demultiplexing: on.
Constructing classification system...
  Parsing taxon names file: protein.names... Done.
  Parsing taxon names file: enzrxn.names... Done.
  Parsing taxon names file: reaction.names... Done.
  Parsing taxon names file: pathway.names... Done.
  Parsing taxon names file: class.names... Done.
  Parsing simple map file: uniref.map.xz... Done.
  Parsing simple map file: protein.map... Done.
  Parsing simple map file: protein2enzrxn.map... Done.
  Parsing simple map file: enzrxn2reaction.map... Done.
  Parsing simple map file: reaction2pathway.map... Done.
  Parsing simple map file: pathway2class.map... Done.
Classification system constructed.
  Total number of classification units: 47386453.
Reading gene coordinates... Done.
  Total number of host sequences: 10575.
Classification will operate on these ranks: protein, enzrxn, reaction, pathway, class.
Parsing alignment file A7.bowtie2.sam . Done.
  Number of sequences classified: 0.
Classification completed.
Format of output feature table(s): TSV.
Writing output profiles in TSV format...
  Rank: class, samples: 0, features: 0.
  Rank: enzrxn, samples: 0, features: 0.
  Rank: pathway, samples: 0, features: 0.
  Rank: protein, samples: 0, features: 0.
  Rank: reaction, samples: 0, features: 0.
Profiles written.
Task completed.
```

As for the data processing steps from raw  data to SAM file, raw fastq files go through adapter trimming and human sequences removing before aligned with shogun(`-a bowtie2`).  All of my samples got non sequences classified.
Is there a working SAM file that I can use to produce a meaningful result? As I'm not sure whether it's my data just got no sequences classified or I need to consider adjusting the parameters. Thanks a lot!

**Comment by qiyunzhu** [comment]
Hi @popucui Thanks for your interest in our program. We also experienced the issue of low classification rate with MetaCyc in some instances, but completely empty outputs are not anticipated. Perhaps some upstream steps need to be adjusted. As a sanity check, if you replace `--rank protein,enzrxn,reaction,pathway,class` with `--rank none,uniref`, will you see some results?

**Comment by popucui** [comment]
Hi @qiyunzhu  Thanks for your reply.
It turns out that the [shogun database](https://raw.githubusercontent.com/knights-lab/SHOGUN/master/docs/shogun_db_links.txt) used in shogun align is the reason I got empty results in `classify`. After I switched to [WoL database](https://biocore.github.io/wol/download), I got some sequences classified. Just as you point out, `--rank none,uniref` did improve the number of features in the result. Thanks a lot!

**Comment by qiyunzhu** [comment]
@popucui Thank you for your feedback. I am glad to know that things are improved. We are working on integrating new databases (KEGG, EggNOG, OrthoDB, etc.) as well as improving the mapping to existing databases (in particular, MetaCyc). We will keep you undated once they are in place for use.
